// apps/store/src/app/pages/game-detail/game-detail.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { GameService } from '../../services/game.service';
import { ImageService } from '../../services/image.service';
import { GameResponse, GameSkuResponse } from '@neversion/api-client';

@Component({
  selector: 'app-game-detail',
  templateUrl: './game-detail.component.html',
  styleUrls: ['./game-detail.component.css']
})
export class GameDetailComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly gameService = inject(GameService);
  private readonly imageService = inject(ImageService);

  game?: GameResponse;
  skus: GameSkuResponse[] = [];
  loading = true;
  error: string | null = null;

  ngOnInit(): void {
    this.route.paramMap.subscribe(params => {
      const slug = params.get('slug');
      if (slug) {
        this.loadGame(slug);
      } else {
        this.error = 'Slug de juego no proporcionado';
        this.loading = false;
      }
    });
  }

  private loadGame(slug: string): void {
    this.loading = true;
    this.error = null;

    this.gameService.getGameBySlug(slug).subscribe({
      next: (game) => {
        this.game = game;
        this.loadSkus(slug);
      },
      error: (err) => {
        console.error('Error loading game by slug:', err);
        this.error = 'No se encontró el juego solicitado.';
        this.loading = false;
      }
    });
  }

  private loadSkus(slug: string): void {
    this.gameService.getGameSkusBySlug(slug).subscribe({
      next: (skus) => {
        // Sort by price ascending for display
        this.skus = [...skus].sort((a, b) => (a.price || 0) - (b.price || 0));
        this.loading = false;
      },
      error: (err) => {
        console.error('Error loading SKUs:', err);
        this.loading = false;
      }
    });
  }

  resolveImageUrl(url?: string): string {
    return this.imageService.resolveServiceImageUrl(url);
  }

  contactToBuy(sku: GameSkuResponse): void {
    const gameName = this.game?.name || 'Juego';
    const text = `Quiero comprar: *${sku.name}* (${gameName}) - Q${sku.price}. Por favor necesito la información de pago.`;
    const message = encodeURIComponent(text);
    window.open(`https://wa.me/message/WEOAAOMZ5XU3I1?text=${message}`, '_blank');
  }

  goBack(): void {
    this.router.navigate(['/games']);
  }
}

<div class="game-detail-page bg-light min-vh-100 pb-5">
    <!-- Header with game info -->
    <div class="bg-primary text-white py-5 mb-4 shadow-sm"
         style="background: linear-gradient(135deg, var(--primary-color) 0%, #1a1a1a 100%);">
        <div class="container py-4">
            <button class="btn btn-outline-light btn-sm mb-3" (click)="goBack()">
                <i class="bi bi-arrow-left me-1"></i> Volver a juegos
            </button>

            @if (loading) {
                <div class="text-center py-3">
                    <div class="spinner-border text-white" role="status"></div>
                    <p class="mt-2 mb-0">Cargando juego...</p>
                </div>
            } @else if (game) {
                <div class="d-flex align-items-center gap-4 flex-column flex-md-row">
                    <div class="bg-white rounded-4 p-3 shadow-sm" style="width: 120px; height: 120px; flex-shrink: 0;">
                        <img [src]="resolveImageUrl(game.imageUrl)"
                             [alt]="game.name"
                             class="img-fluid"
                             style="object-fit: contain; width: 100%; height: 100%;">
                    </div>
                    <div>
                        <h1 class="display-5 fw-bold mb-2">{{ game.name }}</h1>
                        <p class="lead opacity-75 mb-0">Selecciona la recarga que deseas comprar.</p>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="container">
        @if (error) {
            <div class="text-center py-5">
                <div class="mb-4">
                    <i class="bi bi-exclamation-circle text-muted opacity-25" style="font-size: 6rem;"></i>
                </div>
                <h3 class="fw-bold text-muted">{{ error }}</h3>
                <button class="btn btn-primary px-4 mt-3" (click)="goBack()">Volver a juegos</button>
            </div>
        } @else if (loading) {
            <div class="text-center py-5">
                <div class="spinner-border text-primary" role="status"></div>
                <p class="mt-2 text-muted">Cargando recargas...</p>
            </div>
        } @else if (skus.length > 0) {
            <!-- SKUs Grid -->
            <div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5 g-3 g-md-4">
                <div class="col" *ngFor="let sku of skus">
                    <div class="card h-100 border-0 shadow-sm rounded-4 overflow-hidden sku-card transition-all">
                        <div class="p-2 p-sm-3">
                            <div class="ratio ratio-1x1 bg-white rounded-4 overflow-hidden p-2 p-sm-3">
                                <img [src]="resolveImageUrl(sku.imageUrl)"
                                     [alt]="sku.name"
                                     class="img-fluid"
                                     style="object-fit: contain;">
                            </div>
                        </div>

                        <div class="card-body pt-0 px-2 px-sm-3 pb-3 pb-sm-4">
                            <h6 class="fw-bold mb-2 text-dark" style="font-size: clamp(0.8rem, 1.8vw, 1rem);">{{ sku.name }}</h6>

                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <div class="price-box">
                                    <span class="small text-muted d-block" style="font-size: clamp(0.6rem, 1.5vw, 0.75rem);">Precio</span>
                                    <span class="fw-bold text-primary mb-0" style="font-size: clamp(0.9rem, 2vw, 1.15rem);">Q{{ sku.price | number:'1.2-2' }}</span>
                                </div>
                            </div>

                            <div class="border-top pt-3">
                                <button (click)="contactToBuy(sku)" class="btn btn-success btn-sm w-100 fw-bold" style="font-size: clamp(0.7rem, 1.8vw, 0.85rem);">
                                    <i class="bi bi-whatsapp me-1"></i>
                                    Solicitar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        } @else {
            <!-- Empty State - no SKUs -->
            <div class="text-center py-5">
                <div class="mb-4">
                    <i class="bi bi-coin text-muted opacity-25" style="font-size: 6rem;"></i>
                </div>
                <h3 class="fw-bold text-muted">Sin recargas disponibles</h3>
                <p class="text-muted fs-5">Este juego aún no tiene recargas configuradas. Vuelve pronto.</p>
                <button class="btn btn-primary px-4 mt-3" (click)="goBack()">Ver otros juegos</button>
            </div>
        }
    </div>
</div>

// apps/store/src/pages/GameDetail.tsx
import { useParams, useNavigate } from 'react-router-dom'
import { useGames, useGameSkus } from '../hooks/useQueries'
import { SectionHeader } from '../components/ui/SectionHeader'
import { getWhatsAppLink } from '../config/constants'
import { resolveServiceImageUrl } from '../lib/image'
import { ArrowLeft, MessageCircle, Loader2, AlertCircle, Sparkles, Gamepad2 } from 'lucide-react'

export function GameDetail() {
  const { slug } = useParams<{ slug: string }>()
  const navigate = useNavigate()

  const { data: games, isLoading: loadingGames } = useGames()
  const { data: skus, isLoading: loadingSkus, error: errorSkus } = useGameSkus(slug)

  const game = games?.find(g => g.slug === slug)

  const handleContactToBuy = (sku: { name: string; price: number }) => {
    const gameName = game?.name || 'Juego'
    const text = `Hola Neversion, quiero comprar el paquete: *${sku.name}* (${gameName}) - Precio: Q${sku.price}. Por favor envíenme los datos de pago.`
    const url = getWhatsAppLink(text)
    window.open(url, '_blank')
  }

  return (
    <div className="max-w-7xl mx-auto px-4 py-12 animate-fade-up space-y-10">
      {/* Back button */}
      <div>
        <button
          onClick={() => navigate(-1)}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-[#131623] hover:bg-[#1a1d2e] text-[#7a7d90] hover:text-white border border-[#252838] text-xs font-semibold transition-all cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Volver al Catálogo</span>
        </button>
      </div>

      {/* Game Header */}
      {loadingGames ? (
        <div className="py-12 flex justify-center text-[#F5A623]">
          <Loader2 className="w-8 h-8 animate-spin" />
        </div>
      ) : game ? (
        <div className="bg-[#131623] border border-[#252838] rounded-3xl p-8 shadow-2xl flex flex-col sm:flex-row items-center gap-6 relative overflow-hidden">
          <div className="w-24 h-24 rounded-2xl bg-white/5 border border-[#252838] p-2 flex items-center justify-center shrink-0 overflow-hidden">
            {game.imageUrl ? (
              <img
                src={resolveServiceImageUrl(game.imageUrl)}
                alt={game.name}
                className="w-full h-full object-contain"
              />
            ) : (
              <Gamepad2 className="w-12 h-12 text-[#107C10]" />
            )}
          </div>

          <div className="text-center sm:text-left">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#107C10]/20 text-[#107C10] text-[11px] font-bold uppercase tracking-wider mb-2">
              <Sparkles className="w-3.5 h-3.5" />
              <span>Recargas & Pases Oficiales</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-white">{game.name}</h1>
            <p className="text-xs sm:text-sm text-[#7a7d90] mt-1">
              Selecciona el paquete de diamantes, monedas o pases que deseas recargar.
            </p>
          </div>
        </div>
      ) : (
        <div className="p-6 rounded-2xl bg-amber-500/10 border border-amber-500/30 text-amber-400 text-center text-xs">
          No se encontró la información del juego solicitado.
        </div>
      )}

      {/* Packages / SKUs Grid */}
      <section className="space-y-6">
        <SectionHeader
          label="Paquetes Disponibles"
          title={`Recargas para ${game?.name || 'este juego'}`}
          sub="Entrega directa por ID de jugador. Activación rápida y segura."
        />

        {loadingSkus && (
          <div className="py-16 flex flex-col items-center justify-center gap-3 text-[#7a7d90]">
            <Loader2 className="w-8 h-8 animate-spin text-[#F5A623]" />
            <span className="text-sm">Consultando paquetes en Supabase...</span>
          </div>
        )}

        {errorSkus && (
          <div className="p-6 rounded-2xl bg-red-500/10 border border-red-500/30 text-red-400 text-center space-y-2">
            <AlertCircle className="w-8 h-8 mx-auto" />
            <h3 className="font-bold text-base">Error al cargar los paquetes</h3>
            <p className="text-xs">{(errorSkus as Error)?.message}</p>
          </div>
        )}

        {!loadingSkus && !errorSkus && (
          <>
            {!skus || skus.length === 0 ? (
              <div className="py-16 text-center text-[#7a7d90] bg-[#131623] border border-[#252838] rounded-2xl p-8 space-y-3">
                <Gamepad2 className="w-12 h-12 mx-auto text-[#252838]" />
                <h4 className="font-bold text-white text-base">Sin paquetes configurados</h4>
                <p className="text-xs max-w-md mx-auto">
                  Actualmente no hay paquetes o SKUs activos para este juego en la base de datos.
                </p>
              </div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
                {skus.map(sku => (
                  <div
                    key={sku.id}
                    className="bg-[#131623] border border-[#252838] hover:border-[#F5A623]/50 rounded-2xl p-5 flex flex-col justify-between transition-all duration-300 hover:-translate-y-1 shadow-xl group"
                  >
                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <span className="text-[10px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full bg-[#F5A623]/15 text-[#F5A623]">
                          {sku.code || 'SKU'}
                        </span>
                      </div>

                      {sku.imageUrl && (
                        <div className="w-full h-24 rounded-xl bg-white/5 border border-[#252838] p-2 mb-3 flex items-center justify-center overflow-hidden">
                          <img
                            src={resolveServiceImageUrl(sku.imageUrl)}
                            alt={sku.name}
                            className="max-h-full object-contain"
                          />
                        </div>
                      )}

                      <h3 className="font-bold text-white text-base leading-tight mb-2">
                        {sku.name}
                      </h3>
                    </div>

                    <div className="pt-4 border-t border-[#252838] space-y-3">
                      <div>
                        <span className="text-[10px] uppercase text-[#7a7d90] font-semibold block">Precio</span>
                        <div className="font-[Barlow_Condensed] text-2xl font-bold text-white">
                          Q{sku.price}
                        </div>
                      </div>

                      <button
                        onClick={() => handleContactToBuy(sku)}
                        className="w-full py-2.5 rounded-xl bg-emerald-500/15 hover:bg-emerald-500 text-emerald-400 hover:text-[#0d0e18] font-bold text-xs flex items-center justify-center gap-2 transition-all cursor-pointer"
                      >
                        <MessageCircle className="w-4 h-4" />
                        <span>Solicitar por WhatsApp</span>
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </>
        )}
      </section>
    </div>
  )
}
