// apps/store/src/pages/Login.tsx
import { useState } from 'react'
import { useNavigate, useSearchParams, Link } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import {
  Lock,
  Mail,
  User,
  Phone,
  Eye,
  EyeOff,
  AlertCircle,
  CheckCircle2,
  Loader2,
  ArrowRight,
} from 'lucide-react'

export function Login() {
  const [mode, setMode] = useState<'login' | 'register'>('login')
  const [showPassword, setShowPassword] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)

  // Login form state
  const [loginEmail, setLoginEmail] = useState('')
  const [loginPassword, setLoginPassword] = useState('')

  // Register form state
  const [regName, setRegName] = useState('')
  const [regLastname, setRegLastname] = useState('')
  const [regEmail, setRegEmail] = useState('')
  const [regPhone, setRegPhone] = useState('')
  const [regPassword, setRegPassword] = useState('')
  const [regAgree, setRegAgree] = useState(false)

  const { login, register, loginWithGoogle, isLoading } = useAuth()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const returnUrl = searchParams.get('returnUrl') || '/customer-panel'

  const handleLoginSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)
    setSuccess(null)

    const res = await login(loginEmail, loginPassword)
    if (res.success) {
      navigate(returnUrl)
    } else if (res.error) {
      setError(res.error)
    }
  }

  const handleRegisterSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!regAgree) return
    setError(null)
    setSuccess(null)

    const res = await register({
      name: regName,
      lastname: regLastname,
      email: regEmail,
      phone: `+502${regPhone.trim()}`,
      password: regPassword,
      checkCookies: regAgree,
    })

    if (res.success) {
      setSuccess('¡Cuenta creada exitosamente! Ya puedes iniciar sesión.')
      setMode('login')
      setLoginEmail(regEmail)
    } else if (res.error) {
      setError(res.error)
    }
  }

  return (
    <div className="min-h-[80vh] flex items-center justify-center px-4 py-12">
      <div className="w-full max-w-md bg-[#131623] border border-[#252838] rounded-2xl p-6 sm:p-8 shadow-2xl animate-fade-up">
        {/* Header Tabs */}
        <div className="flex border-b border-[#252838] mb-6">
          <button
            type="button"
            onClick={() => {
              setMode('login')
              setError(null)
              setSuccess(null)
            }}
            className={`flex-1 py-3 font-bold text-sm text-center border-b-2 transition-all cursor-pointer ${
              mode === 'login'
                ? 'border-[#F5A623] text-white'
                : 'border-transparent text-[#7a7d90] hover:text-[#b0b3c6]'
            }`}
          >
            Iniciar Sesión
          </button>
          <button
            type="button"
            onClick={() => {
              setMode('register')
              setError(null)
              setSuccess(null)
            }}
            className={`flex-1 py-3 font-bold text-sm text-center border-b-2 transition-all cursor-pointer ${
              mode === 'register'
                ? 'border-[#F5A623] text-white'
                : 'border-transparent text-[#7a7d90] hover:text-[#b0b3c6]'
            }`}
          >
            Registrarse
          </button>
        </div>

        {/* Notifications */}
        {error && (
          <div className="mb-5 p-3 rounded-xl bg-red-500/10 border border-red-500/30 text-red-400 text-xs flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {success && (
          <div className="mb-5 p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 shrink-0" />
            <span>{success}</span>
          </div>
        )}

        {/* Google OAuth button */}
        <button
          type="button"
          onClick={() => loginWithGoogle()}
          disabled={isLoading}
          className="w-full py-2.5 px-4 mb-6 rounded-xl bg-[#1a1d2e] hover:bg-[#22263d] border border-[#252838] text-white text-xs font-semibold flex items-center justify-center gap-2.5 transition-all cursor-pointer"
        >
          <svg className="w-4 h-4" viewBox="0 0 24 24">
            <path
              fill="#EA4335"
              d="M12 5c1.6 0 3 .6 4.1 1.7l3.1-3.1C17.3 1.8 14.8 1 12 1 7.4 1 3.5 3.6 1.6 7.4l3.7 2.9C6.2 7.2 8.9 5 12 5z"
            />
            <path
              fill="#4285F4"
              d="M23.5 12.3c0-.8-.1-1.7-.2-2.3H12v4.6h6.5c-.3 1.5-1.1 2.8-2.4 3.7l3.7 2.9c2.2-2 3.7-5 3.7-8.9z"
            />
            <path
              fill="#FBBC05"
              d="M5.3 14.7c-.2-.7-.4-1.5-.4-2.7s.1-2 .4-2.7L1.6 6.4C.6 8.4 0 10.6 0 13s.6 4.6 1.6 6.6l3.7-4.9z"
            />
            <path
              fill="#34A853"
              d="M12 23c3.2 0 6-1.1 8-3l-3.7-2.9c-1.1.7-2.5 1.2-4.3 1.2-3.1 0-5.8-2.2-6.7-5.3L1.6 16c1.9 3.8 5.8 7 10.4 7z"
            />
          </svg>
          <span>Continuar con Google</span>
        </button>

        <div className="relative flex items-center justify-center mb-6">
          <div className="border-t border-[#252838] w-full" />
          <span className="bg-[#131623] px-3 text-[11px] uppercase font-bold text-[#7a7d90] absolute">
            o con correo
          </span>
        </div>

        {/* Login Form */}
        {mode === 'login' ? (
          <form onSubmit={handleLoginSubmit} className="space-y-4">
            <div>
              <label className="block text-xs font-semibold text-[#b0b3c6] mb-1">
                Correo Electrónico
              </label>
              <div className="relative flex items-center">
                <Mail className="w-4 h-4 text-[#7a7d90] absolute left-3" />
                <input
                  type="email"
                  placeholder="correo@ejemplo.com"
                  value={loginEmail}
                  onChange={e => setLoginEmail(e.target.value)}
                  className="w-full bg-[#1a1d2e] border border-[#252838] rounded-xl pl-10 pr-4 py-2.5 text-sm text-white placeholder-[#7a7d90] focus:outline-none focus:border-[#F5A623]"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-[#b0b3c6] mb-1">
                Contraseña
              </label>
              <div className="relative flex items-center">
                <Lock className="w-4 h-4 text-[#7a7d90] absolute left-3" />
                <input
                  type={showPassword ? 'text' : 'password'}
                  placeholder="••••••••"
                  value={loginPassword}
                  onChange={e => setLoginPassword(e.target.value)}
                  className="w-full bg-[#1a1d2e] border border-[#252838] rounded-xl pl-10 pr-10 py-2.5 text-sm text-white placeholder-[#7a7d90] focus:outline-none focus:border-[#F5A623]"
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(v => !v)}
                  className="absolute right-3 text-[#7a7d90] hover:text-white"
                >
                  {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-3 rounded-xl bg-[#F5A623] hover:bg-[#e09516] text-[#0d0e18] font-bold text-sm flex items-center justify-center gap-2 transition-all cursor-pointer shadow-lg shadow-[#F5A623]/20"
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Ingresando...</span>
                </>
              ) : (
                <>
                  <span>Ingresar a Mi Cuenta</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </form>
        ) : (
          /* Register Form */
          <form onSubmit={handleRegisterSubmit} className="space-y-3.5">
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-semibold text-[#b0b3c6] mb-1">Nombre</label>
                <input
                  type="text"
                  placeholder="Alex"
                  value={regName}
                  onChange={e => setRegName(e.target.value)}
                  className="w-full bg-[#1a1d2e] border border-[#252838] rounded-xl px-3 py-2 text-sm text-white placeholder-[#7a7d90] focus:outline-none focus:border-[#F5A623]"
                  required
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-[#b0b3c6] mb-1">Apellido</label>
                <input
                  type="text"
                  placeholder="García"
                  value={regLastname}
                  onChange={e => setRegLastname(e.target.value)}
                  className="w-full bg-[#1a1d2e] border border-[#252838] rounded-xl px-3 py-2 text-sm text-white placeholder-[#7a7d90] focus:outline-none focus:border-[#F5A623]"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-[#b0b3c6] mb-1">
                Correo Electrónico
              </label>
              <input
                type="email"
                placeholder="correo@ejemplo.com"
                value={regEmail}
                onChange={e => setRegEmail(e.target.value)}
                className="w-full bg-[#1a1d2e] border border-[#252838] rounded-xl px-3 py-2 text-sm text-white placeholder-[#7a7d90] focus:outline-none focus:border-[#F5A623]"
                required
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-[#b0b3c6] mb-1">
                WhatsApp (Guatemala)
              </label>
              <div className="relative flex items-center">
                <span className="absolute left-3 text-xs font-bold text-[#7a7d90] select-none">
                  +502
                </span>
                <input
                  type="tel"
                  placeholder="51234567"
                  value={regPhone}
                  onChange={e => setRegPhone(e.target.value.replace(/\D/g, '').slice(0, 8))}
                  className="w-full bg-[#1a1d2e] border border-[#252838] rounded-xl pl-14 pr-4 py-2 text-sm text-white placeholder-[#7a7d90] focus:outline-none focus:border-[#F5A623]"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-[#b0b3c6] mb-1">Contraseña</label>
              <input
                type="password"
                placeholder="Mínimo 6 caracteres"
                value={regPassword}
                onChange={e => setRegPassword(e.target.value)}
                className="w-full bg-[#1a1d2e] border border-[#252838] rounded-xl px-3 py-2 text-sm text-white placeholder-[#7a7d90] focus:outline-none focus:border-[#F5A623]"
                minLength={6}
                required
              />
            </div>

            <label className="flex items-start gap-2 cursor-pointer select-none pt-1">
              <input
                type="checkbox"
                checked={regAgree}
                onChange={e => setRegAgree(e.target.checked)}
                className="mt-0.5 rounded border-[#252838] bg-[#1a1d2e] text-[#F5A623] focus:ring-0"
                required
              />
              <span className="text-[11px] text-[#7a7d90]">
                Acepto los términos del servicio y autorizo el contacto por WhatsApp para entrega de accesos.
              </span>
            </label>

            <button
              type="submit"
              disabled={isLoading || !regAgree}
              className="w-full py-3 rounded-xl bg-[#F5A623] hover:bg-[#e09516] text-[#0d0e18] font-bold text-sm flex items-center justify-center gap-2 transition-all cursor-pointer shadow-lg shadow-[#F5A623]/20"
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Registrando...</span>
                </>
              ) : (
                <>
                  <span>Crear mi Cuenta</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </form>
        )}
      </div>
    </div>
  )
}

// apps/store/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService, RegisterFormData } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  isLoginMode: boolean = true;
  showPassword: boolean = false;
  loginForm!: FormGroup;
  registerForm!: FormGroup;
  
  isLoading$ = this.authService.isLoading$;
  errorMessage: string | null = null;
  successMessage: string | null = null;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.initForms();
  }

  private initForms(): void {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });

    this.registerForm = this.fb.group({
      name: ['', Validators.required],
      lastname: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      phone: ['', [Validators.required, Validators.pattern(/^\d+$/)]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      checkNewsletter: [false],
      checkCookies: [false, Validators.requiredTrue]
    });
  }

  togglePassword(): void {
    this.showPassword = !this.showPassword;
  }

  onLoginSubmit(): void {
    if (this.loginForm.invalid) return;

    this.errorMessage = null;
    this.successMessage = null;
    const { email, password } = this.loginForm.value;
    
    this.authService.login(email, password).subscribe({
      next: (result) => {
        if (result.success && result.user) {
          this.handleRedirect(result.user.role);
        } else {
          this.errorMessage = result.error || 'Credenciales inválidas.';
        }
      }
    });
  }

  onRegisterSubmit(): void {
    if (this.registerForm.invalid) return;

    this.errorMessage = null;
    this.successMessage = null;
    this.authService.register(this.registerForm.value as RegisterFormData).subscribe({
      next: (result) => {
        if (result.success) {
          this.successMessage = '¡Registro exitoso! Por favor inicia sesión con tus nuevos accesos.';
          this.isLoginMode = true; // Redirect to login
          this.registerForm.reset();
        } else {
          this.errorMessage = result.error || 'Error al registrarse.';
        }
      }
    });
  }

  private handleRedirect(role: string): void {
    if (role === 'client') {
      this.successMessage = '¡Bienvenido de nuevo!';
      setTimeout(() => {
        this.router.navigate(['/customer-panel']);
      }, 1500);
    } else {
      alert('Bienvenido. Redirigiendo al Panel de Administración...');
      window.location.href = '/panel';
    }
  }
}

<section class="login-section d-flex align-items-center min-vh-100 py-5 bg-light">
    <div class="container">
        <div class="row justify-content-center">
            <!-- Adjusted column widths: wider for registration, more compact for login -->
            <div [class]="isLoginMode ? 'col-12 col-md-6 col-lg-4' : 'col-12 col-md-8 col-lg-6 col-xl-5'">

                <div class="card shadow-lg border-0 rounded-5 overflow-hidden bg-white">
                    <div class="card-body p-4 p-md-5">

                        <!-- Error Message Alert -->
                        <div *ngIf="errorMessage" class="alert alert-danger border-0 rounded-4 small py-3 mb-4 d-flex align-items-center">
                            <i class="bi bi-exclamation-circle-fill me-2"></i>
                            {{ errorMessage }}
                        </div>

                        <!-- Success Message Toast/Alert -->
                        <div *ngIf="successMessage" class="alert alert-success border-0 rounded-4 small py-3 mb-4 d-flex align-items-center shadow-sm">
                            <i class="bi bi-check-circle-fill me-2 fs-5"></i>
                            <span class="fw-bold">{{ successMessage }}</span>
                        </div>

                        <!-- Login Mode -->
                        <div *ngIf="isLoginMode">
                            <div class="text-center mb-5">
                                <img src="/assets/logo_neversion.svg" alt="Neversion Logo" class="mb-4 opacity-75" style="height: 60px; filter: invert(1);">
                                <h2 class="h3 text-dark fw-bold mb-1">Bienvenido</h2>
                                <p class="text-muted small">Ingresa tus credenciales para acceder</p>
                            </div>

                            <form [formGroup]="loginForm" (ngSubmit)="onLoginSubmit()">
                                <!-- Email Input -->
                                <div class="mb-4">
                                    <label for="loginEmail" class="form-label small fw-bold text-uppercase text-muted letter-spacing-1">Correo electrónico</label>
                                    <div class="input-group">
                                        <span class="input-group-text bg-light border-end-0 text-muted" style="width: 46px; min-width: 46px; justify-content: center;">
                                            <i class="bi bi-envelope"></i>
                                        </span>
                                        <input type="email" class="form-control bg-light border-start-0 ps-0" id="loginEmail" formControlName="email"
                                            [class.is-invalid]="loginForm.get('email')?.invalid && loginForm.get('email')?.touched"
                                            placeholder="ejemplo@correo.com">
                                    </div>
                                </div>

                                <!-- Password Input -->
                                <div class="mb-2">
                                    <label for="loginPassword" class="form-label small fw-bold text-uppercase text-muted letter-spacing-1">Contraseña</label>
                                    <div class="input-group">
                                        <span class="input-group-text bg-light border-end-0 text-muted" style="width: 46px; min-width: 46px; justify-content: center;">
                                            <i class="bi bi-lock"></i>
                                        </span>
                                        <input [type]="showPassword ? 'text' : 'password'"
                                            class="form-control bg-light border-start-0 border-end-0 ps-0" id="loginPassword" formControlName="password"
                                            [class.is-invalid]="loginForm.get('password')?.invalid && loginForm.get('password')?.touched"
                                            placeholder="••••••••">
                                        <span class="input-group-text bg-light border-start-0 cursor-pointer text-primary fw-bold small"
                                            (click)="togglePassword()">
                                            <i [class]="showPassword ? 'bi bi-eye-slash' : 'bi bi-eye'"></i>
                                        </span>
                                    </div>
                                </div>

                                <!-- Forgot Password -->
                                <div class="text-end mb-4">
                                    <a href="#" class="small text-decoration-none fw-bold text-primary">¿Olvidaste tu contraseña?</a>
                                </div>

                                <!-- Main Action Button -->
                                <div class="d-grid gap-2 mb-4">
                                    <button type="submit" class="btn btn-primary btn-lg rounded-pill fw-bold py-3 shadow transition-all hover-grow" 
                                            [disabled]="loginForm.invalid || (isLoading$ | async)"
                                            style="background: linear-gradient(135deg, var(--primary-color) 0%, var(--darkest-primary-color) 100%); border: none;">
                                        <span *ngIf="(isLoading$ | async)" class="spinner-border spinner-border-sm me-2" role="status"></span>
                                        {{ (isLoading$ | async) ? 'Iniciando...' : 'Acceder ahora' }}
                                    </button>
                                </div>

                                <!-- Separator -->
                                <div class="separator d-flex align-items-center justify-content-center mb-4">
                                    <span class="border-bottom flex-grow-1 opacity-25"></span>
                                    <span class="text-muted small mx-3 opacity-50">o continúa con</span>
                                    <span class="border-bottom flex-grow-1 opacity-25"></span>
                                </div>

                                <!-- Google Button -->
                                <div class="d-grid gap-2 mb-5">
                                    <button type="button"
                                        class="btn btn-outline-dark btn-lg rounded-pill d-flex align-items-center justify-content-center gap-2 py-2 fw-bold transition-all hover-grow">
                                        <i class="bi bi-google text-danger"></i>
                                        Google
                                    </button>
                                </div>

                                <!-- Footer Text -->
                                <div class="text-center bg-light p-4 rounded-4 mx-n2">
                                    <p class="small text-muted mb-2">¿Aún no tienes una cuenta?</p>
                                    <a href="javascript:void(0)" (click)="isLoginMode = false"
                                        class="fw-bold text-decoration-none text-primary h5 mb-0 d-block">Crear una cuenta</a>
                                </div>
                            </form>

                        </div>

                        <!-- Register Mode -->
                        <div *ngIf="!isLoginMode">
                            <div class="mb-5">
                                <h2 class="h3 text-dark fw-bold mb-1">Crea tu cuenta</h2>
                                <p class="text-muted small">Únete a Neversion y gestiona tus suscripciones.</p>
                            </div>

                            <form [formGroup]="registerForm" (ngSubmit)="onRegisterSubmit()">
                                <!-- Name & Lastname Row -->
                                <div class="row g-3 mb-4">
                                    <div class="col-sm-6">
                                        <label for="regName" class="form-label small fw-bold text-uppercase text-muted letter-spacing-1">Nombre</label>
                                        <input type="text" class="form-control bg-light border-0 py-2 px-3" id="regName" formControlName="name"
                                            [class.is-invalid]="registerForm.get('name')?.invalid && registerForm.get('name')?.touched"
                                            placeholder="Tu nombre">
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="regLastname" class="form-label small fw-bold text-uppercase text-muted letter-spacing-1">Apellido</label>
                                        <input type="text" class="form-control bg-light border-0 py-2 px-3" id="regLastname" formControlName="lastname"
                                            [class.is-invalid]="registerForm.get('lastname')?.invalid && registerForm.get('lastname')?.touched"
                                            placeholder="Tu apellido">
                                    </div>
                                </div>

                                <!-- Email -->
                                <div class="mb-4">
                                    <label for="regEmail" class="form-label small fw-bold text-uppercase text-muted letter-spacing-1">Correo electrónico</label>
                                    <input type="email" class="form-control bg-light border-0 py-2 px-3" id="regEmail" formControlName="email"
                                        [class.is-invalid]="registerForm.get('email')?.invalid && registerForm.get('email')?.touched"
                                        placeholder="ejemplo@correo.com">
                                </div>

                                <!-- Phone -->
                                <div class="mb-4">
                                    <label for="regPhone" class="form-label small fw-bold text-uppercase text-muted letter-spacing-1">Teléfono</label>
                                    <div class="input-group">
                                        <span class="input-group-text bg-light border-0 text-muted fw-bold">+502</span>
                                        <input type="tel" class="form-control bg-light border-0 py-2 ps-1" id="regPhone" formControlName="phone"
                                            [class.is-invalid]="registerForm.get('phone')?.invalid && registerForm.get('phone')?.touched"
                                            placeholder="12345678">
                                    </div>
                                </div>

                                <!-- Password -->
                                <div class="mb-4">
                                    <label for="regPassword" class="form-label small fw-bold text-uppercase text-muted letter-spacing-1">Contraseña</label>
                                    <div class="input-group mb-2">
                                        <input [type]="showPassword ? 'text' : 'password'"
                                            class="form-control bg-light border-0 py-2 ps-3" id="regPassword" formControlName="password"
                                            [class.is-invalid]="registerForm.get('password')?.invalid && registerForm.get('password')?.touched"
                                            placeholder="Mínimo 6 caracteres">
                                        <span class="input-group-text bg-light border-0 cursor-pointer text-primary px-3"
                                            (click)="togglePassword()">
                                            <i [class]="showPassword ? 'bi bi-eye-slash' : 'bi bi-eye'"></i>
                                        </span>
                                    </div>
                                    <div class="small text-primary fw-bold d-flex align-items-center">
                                        <i class="bi bi-shield-lock me-2"></i>
                                        Recuerda guardar tu contraseña para acceder más adelante.
                                    </div>
                                </div>

                                <!-- Checkboxes -->
                                <div class="mb-4 p-3 bg-light rounded-4">
                                    <div class="form-check mb-2">
                                        <input type="checkbox" class="form-check-input" id="checkNewsletter" formControlName="checkNewsletter">
                                        <label class="form-check-label small text-muted lh-sm" for="checkNewsletter">
                                            Acepto recibir correos con información sobre mis suscripciones y ofertas.
                                        </label>
                                    </div>

                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" id="checkCookies" formControlName="checkCookies"
                                            [class.is-invalid]="registerForm.get('checkCookies')?.invalid && registerForm.get('checkCookies')?.touched">
                                        <label class="form-check-label small text-muted lh-sm" for="checkCookies">
                                            Acepto el uso de cookies y términos de servicio.
                                        </label>
                                    </div>
                                </div>

                                <!-- Submit Button -->
                                <div class="d-grid gap-2 mb-4">
                                    <button type="submit" class="btn btn-primary btn-lg rounded-pill fw-bold py-3 shadow transition-all hover-grow" 
                                            [disabled]="registerForm.invalid || (isLoading$ | async)"
                                            style="background: linear-gradient(135deg, var(--primary-color) 0%, var(--darkest-primary-color) 100%); border: none;">
                                        <span *ngIf="(isLoading$ | async)" class="spinner-border spinner-border-sm me-2" role="status"></span>
                                        {{ (isLoading$ | async) ? 'Creando...' : 'Crear mi cuenta' }}
                                    </button>
                                </div>

                                <!-- Footer Link -->
                                <div class="text-center mt-4">
                                    <span class="small text-muted">¿Ya tienes una cuenta? </span>
                                    <a href="javascript:void(0)" (click)="isLoginMode = true"
                                        class="fw-bold text-decoration-none text-primary">Iniciar Sesión</a>
                                </div>

                            </form>

                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
